spring.application.name=depolyProject

server.port=${PORT:8080}


# data-base connectivity - 
spring.datasource.url=${DB_URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}

# hibernate configuration - 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
